name: Metrics
on:
  metrics:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.contributions.svg
          token: ${{ secrets.UNLEASHED_TOKEN }}
          base: ''
          plugin_contributions: yes
          plugin_contributions_limit: 365
          plugin_contributions_days: 365
          plugin_contributions_load: 'load_date'
